### PR TITLE
Fix media type for push campagin

### PR DESCRIPTION
**Pull request by karensg**

### CODE REVIEW

**Review by thexa4 — COMMENTED** [review]
Why do we need a v1 create, a v3 create but not a v2 create?

**Comment by karensg** [comment]
@thexa4, as far as I see, that is not true?
```
registrations :push_campaign_trivial do
        view 'create', :create_push_trivial_campaign

        versions 1, 2, 3
      end
```

**Comment by thexa4** [comment]
You're right, it's only defined in v1, sorry. Are you sure that the create view you defined in v1 propagates to higher versions?

**Comment by karensg** [comment]
The only difference is filter and self link. As I understand, filter is not something we want to push

**Review by thexa4 — APPROVED** [review]

**Pull request merged**
